name: Build Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.11 python3.11-dev python3.11-venv
          python3.11 -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies from source
        run: |
          python3.11 -m pip install --upgrade pip wheel
          python3.11 -m pip install "setuptools<66"
          python3.11 -m pip install ./acme
          python3.11 -m pip install ./certbot
          python3.11 -m pip install ./certbot-dns-cloudflare
          python3.11 -m pip install pyinstaller

      - name: Create minimal wrapper for PyInstaller
        run: |
          cd certbot
          cat > run_certbot.py << 'EOF'
          from src.certbot.main import main
          import sys
          if __name__ == "__main__":
              sys.exit(main())
          EOF

      - name: Build Certbot executable
        run: |
          cd certbot
          pyinstaller --onefile \
            --name certbot \
            --collect-all certbot \
            --collect-all certbot_dns_cloudflare \
            run_certbot.py
          ls -lh dist/

      - name: Test binary
        run: |
          ./certbot/dist/certbot --version
          ./certbot/dist/certbot plugins

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: certbot/dist/certbot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-amd64:
    runs-on: ubuntu-22.04
    container: centos:7
    steps:
      - name: Install system dependencies
        run: |
          yum -y update
          yum -y install epel-release
          yum -y install python3 python3-devel python3-venv
          python3 -m pip install --upgrade pip setuptools wheel

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies from source
        run: |
          python3 -m pip install "setuptools<66"
          python3 -m pip install ./acme ./certbot ./certbot-dns-cloudflare
          python3 -m pip install pyinstaller

      - name: Create minimal wrapper for PyInstaller
        run: |
          cd certbot
          cat > run_certbot.py << 'EOF'
          from src.certbot.main import main
          import sys
          if __name__ == "__main__":
              sys.exit(main())
          EOF

      - name: Build Certbot executable (amd64)
        run: |
          cd certbot
          pyinstaller --onefile \
            --name certbot-amd64 \
            --collect-all certbot \
            --collect-all certbot_dns_cloudflare \
            run_certbot.py
          ls -lh dist/

      - name: Test binary
        run: |
          ./certbot/dist/certbot-amd64 --version
          ./certbot/dist/certbot-amd64 plugins

      - name: Upload binary (amd64)
        uses: softprops/action-gh-release@v2
        with:
          files: certbot/dist/certbot-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
